Repository Daily-Drip-Dev/Driply, pull requests merged in 2025-01, with the labels that each got.

#19 fix: 기본 폰트 변경
  app/index.css
Labels: bug, frontend

#17 feat: home login route 구현
  app/index.css
  app/layout/HomeLayout/index.tsx
  app/layout/HomeLayout/styles.css.ts
  app/routes/_index.tsx
  public/driply-logo.png
  public/favicon.ico
  public/kakao.png
Labels: feature, frontend

#22 chore: 모바일 개발 환경을 위한 host 환경 추가
  package.json
Labels: chore

#20 feat: 카카오 로그인 구현
  app/component/LogsMain/index.tsx
  app/layout/HomeLayout/index.tsx
  app/routes/_index.tsx
  app/routes/authCallback.tsx
  app/routes/logs.tsx
  package-lock.json
  package.json
  src/supabase/client.js
  src/supabase/client.ts
  src/supabase/constants.ts
  src/supabase/server.ts
  tsconfig.json
Labels: feature, frontend

#27 chore: prettierrc 설정
  .prettierrc
Labels: chore

#30 fix:error route redirect 로직 수정
  app/routes/authCallback.tsx
Labels: bug, frontend

#31 feat: ActionHeader 컴포넌트 구현
  app/component/ActionHeader/ActionHeader.stories.tsx
  app/component/ActionHeader/index.tsx
  app/component/ActionHeader/styles.css.ts
Labels: feature, frontend
