Repository Daily-Drip-Dev/Driply, pull requests merged in 2025-02, with the labels that each got.

#35 feat: RemovableImage 및 ImageList 구현
  app/component/ImageList/ImageList.stories.tsx
  app/component/ImageList/index.tsx
  app/component/ImageList/styles.css.ts
  app/component/RemovableImage/RemovableImage.stories.tsx
  app/component/RemovableImage/index.tsx
  app/component/RemovableImage/styles.css.ts
Labels: feature, frontend

#38 feat: 점수 슬라이더 컴포넌트 구현
  app/component/CoffeeScoreSlider/CoffeeScoreSlider.stories.tsx
  app/component/CoffeeScoreSlider/index.tsx
  app/component/CoffeeScoreSlider/style.css.ts
  src/vanilla-extract/theme.css.ts
Labels: feature, frontend

#34 feat: ImageUploader 컴포넌트 구현
  app/component/ImageUploader/ImageUplodar.stories.tsx
  app/component/ImageUploader/index.tsx
  app/component/ImageUploader/styles.css.ts
Labels: feature, frontend

#40 feat: ImageInputSection구현
  app/component/ImageInputSecton/ImageInputSection.stories.tsx
  app/component/ImageInputSecton/index.tsx
  app/component/ImageInputSecton/styles.css.ts
  package-lock.json
  package.json
  src/store/useCoffeeLogForm.ts
Labels: feature, frontend

#42 feat: LogMetadataCreateSection 구현
  app/component/Input/index.tsx
  app/component/LogMetadataCreateSection/LogMetadataCreateSection.stories.tsx
  app/component/LogMetadataCreateSection/index.tsx
  app/component/LogMetadataCreateSection/styles.css.ts
  app/component/TextArea/index.tsx
  src/store/useCoffeeLogForm.ts
Labels: feature, frontend

#50 feat:[Log Create] ImageInputSection에서의 이미지 DnD 기능 구현
  app/component/ImageInputSecton/ImageInputSection.stories.tsx
  app/component/ImageInputSecton/index.tsx
  app/component/ImageList/ImageList.stories.tsx
  app/component/ImageList/index.tsx
  app/component/ImageList/styles.css.ts
  app/component/RemovableImage/index.tsx
  app/component/SortableImageCard/SortableImageCard.stories.tsx
  app/component/SortableImageCard/index.tsx
  app/component/SortableImageCard/styles.css.ts
  package-lock.json
  package.json
  src/store/useCoffeeLogForm.ts
Labels: feature, frontend

#46 build: GCP, Docker 이용한 CD구축
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
  package-lock.json
Labels: build

#52 feat: 커피 점수 입력 스텝
  app/component/CoffeeScoreSlider/index.tsx
  app/component/CoffeeScoreStep/index.tsx
  app/component/CoffeeScoreStep/style.css.ts
  app/component/Funnel/index.tsx
  app/component/Funnel/styles.css.ts
  app/layout/LogCreateLayout/index.tsx
  src/constants/index.ts
  src/store/useCoffeeLogForm.ts
Labels: feature, frontend

#53 feat: 커피 메타 정보 입력 스텝
  app/component/CoffeeMetaStep/index.tsx
  app/component/CoffeeMetaStep/styles.css.ts
  app/component/CoffeeScoreSlider/style.css.ts
  app/component/Funnel/index.tsx
  app/component/ImageInputSecton/index.tsx
  app/layout/LogCreateLayout/index.tsx
  package-lock.json
  package.json
  src/store/useCoffeeLogForm.ts
Labels: feature
